apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elastic
  namespace: elastic
spec:
  version: 7.12.1
  http:
    service:
      spec:
        type: NodePort
    tls:
      selfSignedCertificate:
        disabled: true
  nodeSets:
  - name: master
    count: 1
    podTemplate: 
      spec: 
       containers:
        - name: elasticsearch
          readinessProbe:
            exec:
              command:
              - bash
              - -c
              - /mnt/elastic-internal/scripts/readiness-probe-script.sh
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 12
            successThreshold: 1
            timeoutSeconds: 12
          env:
           - name: ES_JAVA_OPTS
             value: "-Xms4g -Xmx4g"
           - name: READINESS_PROBE_TIMEOUT
             value: "10"
          resources:
            requests:
              cpu: 4
              memory: 8Gi
            limits:
              memory: 8Gi
              cpu: 4  
       initContainers:              
        - name: increase-vm-max-map
          image: busybox
          command: ["sysctl", "-w", "vm.max_map_count=262144"]
          securityContext:
            privileged: true
        - name: increase-fd-ulimit
          image: busybox
          command: ["sh", "-c", "ulimit -n 65536"]
          securityContext:
            privileged: true
        - command:
          - sh
          - -c
          - |
            bin/elasticsearch-plugin remove repository-s3
            bin/elasticsearch-plugin install --batch repository-s3
          name: install-plugins
        - name: add-access-keys
          env:
          - name: AWS_ACCESS_KEY_ID
            value: "${s3_key}" 
          - name: AWS_SECRET_ACCESS_KEY
            value: "${s3_key_id}"
          command:
          - sh
          - -c
          - |
            echo AWS_ACCESS_KEY_ID  | bin/elasticsearch-keystore add --stdin --force s3.client.default.access_key
            echo AWS_SECRET_ACCESS_KEY | bin/elasticsearch-keystore add --stdin --force s3.client.default.secret_key   
       affinity:
           nodeAffinity:
             requiredDuringSchedulingIgnoredDuringExecution:
               nodeSelectorTerms:
               - matchExpressions:
                 - key: failure-domain.beta.kubernetes.io/zone
                   operator: In
                   values:
                   - zone-0                        
    config:   
      xpack.security.authc:
          anonymous:
            username: anonymous
            roles: superuser
            authz_exception: false
      xpack.security.authc.realms:
        native:
          native1:
            order: 1
      node.attr.zone: zone-0
      node.store.allow_mmap: false
      node.ml: false
      node.data: false
      node.master: true
      thread_pool.snapshot.max: 8
      cluster.routing.allocation.awareness.attributes: k8s_node_name,zone 
    volumeClaimTemplates:
      - metadata:
          name: elasticsearch-data
        spec:
          accessModes: [ "ReadWriteOnce" ]
          storageClassName: standard 
          resources:
            requests:
              storage: 100Gi      

  - name: hot
    count: 1
    podTemplate:
      spec:
       containers:
        - name: elasticsearch
          readinessProbe:
            exec:
              command:
              - bash
              - -c
              - /mnt/elastic-internal/scripts/readiness-probe-script.sh
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 12
            successThreshold: 1
            timeoutSeconds: 12
          env:
          - name: ES_JAVA_OPTS
            value: "-Xms4g -Xmx4g"
          - name: READINESS_PROBE_TIMEOUT
            value: "10"
          resources:
            requests:
              cpu: 4
              memory: 8Gi
            limits:
              memory: 8Gi
              cpu: 4  
       initContainers:              
        - name: increase-vm-max-map
          image: busybox
          command: ["sysctl", "-w", "vm.max_map_count=262144"]
          securityContext:
            privileged: true
        - name: increase-fd-ulimit
          image: busybox
          command: ["sh", "-c", "ulimit -n 65536"]
          securityContext:
            privileged: true
        - command:
          - sh
          - -c
          - |
            bin/elasticsearch-plugin remove repository-s3
            bin/elasticsearch-plugin install --batch repository-s3
          name: install-plugins        
        - name: add-access-keys
          env:
          - name: AWS_ACCESS_KEY_ID
            value: "${s3_key}"
          - name: AWS_SECRET_ACCESS_KEY
            value: "${s3_key_id}"
          command:
          - sh
          - -c
          - |
            echo AWS_ACCESS_KEY_ID | bin/elasticsearch-keystore add --stdin --force s3.client.default.access_key
            echo AWS_SECRET_ACCESS_KEY | bin/elasticsearch-keystore add --stdin --force s3.client.default.secret_key
       affinity:
           nodeAffinity:
             requiredDuringSchedulingIgnoredDuringExecution:
               nodeSelectorTerms:
               - matchExpressions:
                 - key: failure-domain.beta.kubernetes.io/zone
                   operator: In
                   values:
                   - zone-1                        
    config:   
      xpack.security.authc:
          anonymous:
            username: anonymous
            roles: superuser
            authz_exception: false
      xpack.security.authc.realms:
        native:
          native1:
            order: 1
      node.attr.zone: zone-1
      node.attr.type: hot
      node.roles: [ data_hot, data_content ]
      node.store.allow_mmap: false
      thread_pool.snapshot.max: 8
      cluster.routing.allocation.awareness.attributes: k8s_node_name,zone  
    volumeClaimTemplates:
      - metadata:
          name: elasticsearch-data
        spec:
          accessModes: [ "ReadWriteOnce" ]
          storageClassName: standard 
          resources:
            requests:
              storage: 100Gi
              
  - name: warm
    count: 1
    podTemplate:
      spec: 
       containers:
        - name: elasticsearch
          readinessProbe:
            exec:
              command:
              - bash
              - -c
              - /mnt/elastic-internal/scripts/readiness-probe-script.sh
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 12
            successThreshold: 1
            timeoutSeconds: 12
          env:
          - name: ES_JAVA_OPTS
            value: "-Xms4g -Xmx4g"
          - name: READINESS_PROBE_TIMEOUT
            value: "10"
          resources:
            requests:
              cpu: 4
              memory: 8Gi
            limits:
              memory: 8Gi
              cpu: 4  
       initContainers:              
        - name: increase-vm-max-map
          image: busybox
          command: ["sysctl", "-w", "vm.max_map_count=262144"]
          securityContext:
            privileged: true
        - name: increase-fd-ulimit
          image: busybox
          command: ["sh", "-c", "ulimit -n 65536"]
          securityContext:
            privileged: true
        - command:
          - sh
          - -c
          - |
            bin/elasticsearch-plugin remove repository-s3
            bin/elasticsearch-plugin install --batch repository-s3
          name: install-plugins
        - name: add-access-keys
          env:
          - name: AWS_ACCESS_KEY_ID
            value: "${s3_key}"
          - name: AWS_SECRET_ACCESS_KEY
            value: "${s3_key_id}"
          command:
          - sh
          - -c
          - |
            echo AWS_ACCESS_KEY_ID | bin/elasticsearch-keystore add --stdin --force s3.client.default.access_key
            echo AWS_SECRET_ACCESS_KEY | bin/elasticsearch-keystore add --stdin --force s3.client.default.secret_key
       affinity:
           nodeAffinity:
             requiredDuringSchedulingIgnoredDuringExecution:
               nodeSelectorTerms:
               - matchExpressions:
                 - key: failure-domain.beta.kubernetes.io/zone
                   operator: In
                   values:
                   - zone-2                        
    config:   
      xpack.security.authc:
          anonymous:
            username: anonymous
            roles: superuser
            authz_exception: false
      xpack.security.authc.realms:
        native:
          native1:
            order: 1
      node.attr.zone: zone-2
      node.roles: data_warm
      thread_pool.snapshot.max: 8
      cluster.routing.allocation.awareness.attributes: k8s_node_name,zone
      node.store.allow_mmap: false  
    volumeClaimTemplates:
      - metadata:
          name: elasticsearch-data
        spec:
          accessModes: [ "ReadWriteOnce" ]
          storageClassName: standard 
          resources:
            requests:
              storage: 200Gi

  - name: cold
    count: 1
    podTemplate:
      spec: 
       containers:
       - name: elasticsearch
         readinessProbe:
           exec:
             command:
             - bash
             - -c
             - /mnt/elastic-internal/scripts/readiness-probe-script.sh
           failureThreshold: 3
           initialDelaySeconds: 10
           periodSeconds: 12
           successThreshold: 1
           timeoutSeconds: 12
         env:
         - name: ES_JAVA_OPTS
           value: "-Xms4g -Xmx4g"
         - name: READINESS_PROBE_TIMEOUT
           value: "10"
         resources:
           requests:
             cpu: 4
             memory: 8Gi
           limits:
             memory: 8Gi
             cpu: 4  
       initContainers:              
        - name: increase-vm-max-map
          image: busybox
          command: ["sysctl", "-w", "vm.max_map_count=262144"]
          securityContext:
            privileged: true
        - name: increase-fd-ulimit
          image: busybox
          command: ["sh", "-c", "ulimit -n 65536"]
          securityContext:
            privileged: true
        - command:
          - sh
          - -c
          - |
            bin/elasticsearch-plugin remove repository-s3
            bin/elasticsearch-plugin install --batch repository-s3
          name: install-plugins
        - name: add-access-keys
          env:
          - name: AWS_ACCESS_KEY_ID
            value: "${s3_key}"
          - name: AWS_SECRET_ACCESS_KEY
            value: "${s3_key_id}"
          command:
          - sh
          - -c
          - |
            echo AWS_ACCESS_KEY_ID | bin/elasticsearch-keystore add --stdin --force s3.client.default.access_key
            echo AWS_SECRET_ACCESS_KEY | bin/elasticsearch-keystore add --stdin --force s3.client.default.secret_key
       affinity:
           nodeAffinity:
             requiredDuringSchedulingIgnoredDuringExecution:
               nodeSelectorTerms:
               - matchExpressions:
                 - key: failure-domain.beta.kubernetes.io/zone
                   operator: In
                   values:
                   - zone-3                        
    config:   
      xpack.security.authc:
          anonymous:
            username: anonymous
            roles: superuser
            authz_exception: false
      xpack.security.authc.realms:
        native:
          native1:
            order: 1
      node.attr.zone: zone-3
      node.roles: data_cold
      thread_pool.snapshot.max: 8
      cluster.routing.allocation.awareness.attributes: k8s_node_name,zone
      node.store.allow_mmap: false
    volumeClaimTemplates:
      - metadata:
          name: elasticsearch-data
        spec:
          accessModes: [ "ReadWriteOnce" ]
          storageClassName: standard 
          resources:
            requests:
              storage: 300Gi
